databases:
  - name: obake-intro_DB
    databaseName: obake-intro_db
    user: obake-intro
    region: singapore

services:
  - type: web
    name: obake-intro
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: obake-intro_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

